services:
  tempconv-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root-secret-password
      MYSQL_DATABASE: tempconv
      MYSQL_USER: tempconv
      MYSQL_PASSWORD: tempconv
    networks:
      - tempconv-net
    volumes:
      - db-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

  tempconv-app:
    image: docker.io/valend/tempconverter:latest
    ports:
      - '80:5000'
    environment:
      DB_USER: tempconv
      DB_PASS: tempconv
      DB_HOST: tempconv-db
      DB_NAME: tempconv
      STUDENT: 'Valentino Divjak'
      COLLEGE: 'Algebra Bernays University'
    networks:
      - tempconv-net
    depends_on:
      - tempconv-db
    deploy:
      replicas: 3
      placement:
        max_replicas_per_node: 1
      restart_policy:
        condition: on-failure

volumes:
  db-data:

networks:
  tempconv-net:

